
name: publish

on: [push]

env:
  container_registry: ghcr.io
  container_path: ${{ github.repository }}
  container_tag: latest

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy the image
        env:
          full_container_url: "${{ env.container_registry }}/${{ env.container_path }}:${{ env.container_tag }}"
        run: |
          docker build . --tag $full_container_url
          docker run $full_container_url
          docker push $full_container_url
