
name: publish

on: [push]

env:
  container_registry: ghcr.io
  container_path: ${{ github.repository }}
  container_tag: latest
  full_container_url: $container_registry/$container_path:$container_tag

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy the image
        run: |
          docker build . --tag $full_container_url
          docker run $full_container_url
          docker push $full_container_url
